include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - legacy/**            # todo lo “legacy”
    - test.off/**          # tests desactivados
    - integration_test.off/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-inference: true
    strict-raw-types: true
    strict-casts: true

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_locals: true
    prefer_const_constructors: true
    unawaited_futures: true
    use_build_context_synchronously: false
