name: bitacora
description: Bitácora inteligente para cuadrillas (oil & gas)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI / estado
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5
  collection: ^1.19.0
  intl: ^0.20.2

  # Almacenamiento y paths
  shared_preferences: ^2.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  file_selector: ^1.0.4
  flutter_secure_storage: ^9.2.1

  # Dispositivo
  camera: ^0.11.2
  camera_windows: ^0.2.1
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  geolocator_windows: ^0.2.3
  package_info_plus: ^8.3.1
  open_filex: ^4.7.0
  wakelock_plus: ^1.2.0

  # Voz a texto
  speech_to_text: ^7.3.0
  speech_to_text_windows: ^1.0.0

  # Notificaciones
  flutter_local_notifications: ^19.4.2

  # Compartir & red
  share_plus: ^12.0.0
  url_launcher: ^6.3.0
  connectivity_plus: ^7.0.0
  flutter_email_sender: ^8.0.0

  # Mapas
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # XLSX
  syncfusion_flutter_xlsio: ^31.2.2
  archive: ^4.0.7
  image: ^4.5.4

  # DB / estado
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  sqlite3: ^2.5.0
  flutter_riverpod: ^2.6.1

  # Utils
  http: ^1.5.0
  uuid: ^4.5.1
  crypto: ^3.0.6
  flutter_colorpicker: ^1.1.0
  logger: ^2.6.1
  cryptography: ^2.7.0
  args: ^2.5.0

  # Tutorial
  showcaseview: ^5.0.1

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_functions: ^6.0.3
  cloud_firestore: ^6.0.3

  # PDF
  pdf: ^3.11.0
  json_schema: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.2
  build_runner: ^2.7.2
  msix: ^3.16.2

flutter:
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: Bitácora
  publisher_display_name: Tu Empresa
  identity_name: com.tu.empresa.bitacora
  capabilities:
    - internetClient
    - webcam
    - microphone
    - location
