name: Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Restore google-services.json
        if: ${{ secrets.GOOGLE_SERVICES_JSON_B64 != '' }}
        run: |
          mkdir -p android/app
          printf "%s" "${{ secrets.GOOGLE_SERVICES_JSON_B64 }}" | base64 -d > android/app/google-services.json

      - run: flutter --version
      - run: flutter pub get
      - run: flutter create --platforms=android --overwrite .

      - run: yes | sdkmanager --licenses

      - run: flutter build apk --debug -v
      - run: flutter build apk --release -v || true

      - uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk
