name: Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter --version
      - run: flutter pub get

      # Crea /android si falta
      - run: flutter create --platforms=android --overwrite .

      # Acepta licencias del SDK
      - run: yes | sdkmanager --licenses

      # Build
      - run: flutter build apk --debug -v
      - run: flutter build apk --release -v || true

      - uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk
